name: Daily Cron Job @ 20 UTC
on:
  schedule:
    - cron: '0 20 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: daily cron job
        run: |
          curl --request POST \
          --url 'https://motivation-quote-generator.fly.dev/api/getQuote' \
